version: "3.8"

services:
  # ==========================
  # MySQL
  # ==========================
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qrson
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3307:3306"
    volumes:
      - qrson_db:/var/lib/mysql

  # ==========================
  # PHP + Apache
  # ==========================
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "81:80"
    volumes:
      - ./src/qrson:/var/www/html
    restart: unless-stopped

volumes:
  qrson_db:
